### ISSUE TITLE
Fresh routes error

### ISSUE THREAD

**Issue by nhrones** [freshframework/fresh#40]
After running fresh routes ...
the **routes.gen.ts** has errors 'Unable to load a local module: ' 'check file path' ...
```js
import * as $0 from "./pagesce/pages/api/joke.ts";
import * as $1 from "./pagesce/pages/index.tsx";
import * as $2 from "./pagesce/pages/[name].tsx";
```
The folder 'pagesce' does not exist.
If I edit  **routes.gen.ts** to remove (pagesce/) 
```js
import * as $0 from "./pages/api/joke.ts";
import * as $1 from "./pages/index.tsx";
import * as $2 from "./pages/[name].tsx";
```
the app runs without errors.

deno 1.11.4 (release, x86_64-pc-windows-msvc)
v8 9.1.269.35
typescript 4.3.2

deployctl 0.3.0

**Comment by nhrones** [comment]
to reproduce ...
```
$ fresh init wxyz
$ cd wxyz
$ code .
```
opened routes.gen.ts
```js
// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./pagesyz/pages/api/joke.ts";
import * as $1 from "./pagesyz/pages/index.tsx";
import * as $2 from "./pagesyz/pages/[name].tsx";

const routes = {
  pages: {
    "./pagesyz/pages/api/joke.ts": $0,
    "./pagesyz/pages/index.tsx": $1,
    "./pagesyz/pages/[name].tsx": $2,
  },
  baseUrl: import.meta.url,
};

export default routes;
```
Note: the extra folder is named ... pages + ${ the last 2 characters of the parent folder name }
this is reproduceable for any folder name given to fresh init

**Comment by nhrones** [comment]
also ...
error in ./pages/[name].tsx line 8
```js
  return <div>Hello {props.params.name}</div>;
```
the 'div' tags are highlighted red and the error message is ...
```
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.deno-ts(7026)
```

**Comment by satyarohith** [comment]
I think I encountered this error before. I can no longer reproduce it on macOS. Can you confirm if re-installing fresh doesn't fix it?
```sh
deno install -A -f --no-check --reload -n fresh https://raw.githubusercontent.com/lucacasonato/fresh/main/cli.ts
```

**Comment by nhrones** [comment]
@satyarohith   reinstall did not fix (win10)
I did a local fix and tested (OK) 

routes.ts  ...
 ```js
// line # 51 added 2 to the href.length   
// from  this 	
const file = toFileUrl(entry.path).href.substring(pagesUrl.href.length);
// to  this 	
const file = toFileUrl(entry.path).href.substring(pagesUrl.href.length + 2);

//  line # 60	removed '/pages'  
// from this	
${files.map((file, i) => `import * as $${i} from "./pages${file}";`).join("\n")}
// to this
${files.map((file, i) => `import * as $${i} from ".${file}";`).join("\n")}

//  line # 65	removed '/pages'  
// from this	
files.map((file, i) => `${JSON.stringify(`./pages${file}`)}: $${i},`)
// to this	
files.map((file, i) => `${JSON.stringify(`.${file}`)}: $${i},`)
```

**Comment by nhrones** [comment]
@satyarohith  I found this

the ...
```js
 toFileUrl(entry.path) 
```
added two extra // 
```js
 href: "file:///C:/...
```
these are then negated by the ...
```js
href.substring(pagesUrl.href.length + 2);
```

**Comment by nhrones** [comment]
@satyarohith 

routes.ts line # 43

```js
// in windows ... this works ...
const pagesUrl = new URL( "file:///" + pagesDir);
// returns "file:///C:/Users/nhron/....."

// this does not ...
const pagesUrl = new URL( pagesDir, "file:///")
// returns "c:\Users\nhron\....."
```
This allows the lengths to match and then all works well.
can you test if this is not the case in linux/mac?

Since ```new URL()``` is a core Deno function, this may be the cause of other issues with Deno in Win10?

**Comment by nhrones** [comment]
@satyarohith   ... new URL()

in Chrome-v8 ...
```
<script>
    	console.log(new URL("c:/docs", "file:///"))
</script>
```
returns      **file:///C:/docs**

in Deno ... 
```
	console.log(new URL("c:/docs", "file:///"))
```
returns      **c:/docs**

Is Deno URL not browser compat? I can see this creating many ;Deno-Windows; Issues!

**Comment by nhrones** [comment]
This is a deno issue. Once deno URL starts passing all tests, this issue will go away.

**Comment by nhrones** [comment]
```js
// routes.ts line 43

// Currently this does not work in Windows10 as Deno URL() constructor is not passing test!
const pagesUrl = new URL( pagesDir, "file:///")
// pagesUrl  will be 'c:/...'

// if we change line 43 to this, everything works as designed.
const pagesUrl = toFileUrl(new URL(pagesDir).href)
// pagesUrl  will be 'file:///c:/...' and then will return proper relative path at line 51

// I think this is what was intended to begin with
```

**Comment by nhrones** [comment]
I've confirmed the issue is Windows10...

VS Code in WSL-Windows-bash(ubuntu)
```
> fresh routes ->
Route manifest generated and written to  /home/ndh/projects/courses/test/routes.gen.ts 
new URL(url, base) will see the above url as 'relative' and so, will add the base 'file:///'
```
```
pages: {
    "./pages/api/joke.ts": $0,
    "./pages/index.tsx": $1,
    "./pages/[name].tsx": $2,
  }	
```

VS Code in native-Windows-Powershell
```
> fresh routes ->
Route manifest generated and written to C:\Users\nhron\Documents\Work\ACTIVE\test\routes.gen.ts
new URL(url, base) sees the above url as absolute, so it will ignore the base 'file://'
```
```
  pages: {
    "./pagesst/pages/api/joke.ts": $0,
    "./pagesst/pages/index.tsx": $1,
    "./pagesst/pages/[name].tsx": $2,
  }	
```
by the way... Chrome/Win10 new URL() will use the 'base' even if the url is absolute!!!
This is not to spec, where node and deno will honor the spec.

from the Web/API/URL docs

	@url param = a string or an element — that represents an absolute or relative URL. 
	If url is a relative URL, base is required,
   	[@base] param =  If url is an absolute URL, a given base will be ignored.

**Comment by lucacasonato** [comment]
@nhrones Thanks for all the info. I have not yet tested fresh on windows - I'll make sure it is all working soon.

**Comment by nhrones** [comment]
My local repo works great with a very simple fix, I'll test it on WSL.  I
just spent hours building a fresh/clean test laptop with WSL2.  It was then
that I discovered the difference in deno.cwd on win and *inix.  I've spent
days studying the URL constructor issue and now I know that both node and
deno are faithful to the spec. It is ChromeWin10 that doesn't.  This was
the opposite of what I had assumed.  Not sure if the URL constructor is
owned by Chromium or V8?  Someone should report it.

Thanks for replying so quickly, I thought I was being a pest.  I'm very
excited about deploy.  I have an animated clock running there (
clock.deno.dev).  I bypassed all the initial errors by writing my own path
parser.
Nick

**Comment by nhrones** [comment]
@lucacasonato 

routes.ts

The new URL() constructor on line#43, will ignor its second param 'file:///', when the first is param is an absolute path.
Deno.cwd() will return an absolute path with a drive letter in Win32.

So, on line #51 the toFileURL() does not seem to care about absolute path and will 
return a true 'file:///...' href which makes the substring on that line inacurate.

The fix at least on Win32, is to subString the final toFileURL.href result to
extract the correct relative path.
  
Since '/pages/' is a constant, you can get the relative path from 'toFileURL.href.lastIndexOf('pages')'
```js
   // old line 51
   const file = toFileUrl(entry.path).href.substring(pagesUrl.href.length);
   // two new lines to replace above
   const fileUrl = toFileUrl(entry.path).href // added this extra step to improve readability
   const file = fileUrl.substring(fileUrl.lastIndexOf('pages'));
```

This will also require the removal of the now redundant 'pages' text on lines #60 and #65  
```js
   // line 60 will now have a redundant               pages
   ${files.map((file, i) => `import * as $${i} from "./pages${file}";`).join("\n")}
   // changed to 
   ${files.map((file, i) => `import * as $${i} from "./${file}";`).join("\n")}
   // same with line 65
```

**Comment by nhrones** [comment]
Closing as there seems to be a lack of interest in supporting Windows.  Using windows? Don't use fresh!

**Comment by sylc** [comment]
This issue should be re-open. it is still happening
