### ISSUE TITLE
expose target options

### ISSUE THREAD

**Issue by aulneau** [freshframework/fresh#43]
Hi there :)

Cool project. It'd be great if you could expose a way to modify the targets that esbuild uses. I have a lib that uses bigints and as a result I get this error ` Big integer literals are not available in the configured target environment ("chrome89", "firefox88", "safari13")`

**Comment by lucacasonato** [comment]
Makes sense! I'll look into it :-)

**Comment by lucacasonato** [comment]
This may actually be resolved by #38
