### ISSUE TITLE
Use Deno.readFile for loading JS and static files

### ISSUE THREAD

**Issue by ry** [freshframework/fresh#44]

**Comment by lucacasonato** [comment]
Deploy needs to support `Deno.readFile` with absolute URLs and `Deno.cwd` first. Implementation can not be portable and correct between CLI and Deploy otherwise.

**Comment by ry** [comment]
straw-person proposal:
```
await Deno.readFile("repo://static/image.jpg")
```
original idea: `Deno.cwd()` returns `/src`
```
/src # repo contents
/src/static/image.jpg 
```
with potentially have some future where we have `/blobs` which maps to GCS... 

Many people use `import.meta.url` and resolve relative to that. 
Currently wont work on deploy because raw.githubusercontent.com url.
Luca proposal: `import.meta.url => "file:///src/src/main.ts"` for files from your repo. Would allow these FS commands to work both in Deploy and locally.

TODO:
1. Change `import.meta.url` to be `file:///src/...`
1. `Deno.readFile("file:///src/static/image.jpg")` accept absolute file URLs
1. `Deno.cwd()` always returns "/src/"

How far do we want to go with this vfs? should we support stat? beyond `/blobs` what else?
