### ISSUE TITLE
Development address not obvious

### ISSUE THREAD

**Issue by sylc** [freshframework/fresh#50]
When starting, the `0.0.0.0:8000` address appear in the terminal.
![image](https://user-images.githubusercontent.com/10268458/131979627-0befc6f8-a561-4ba8-b17b-0696be78c085.png)

 Although when navigating to it, there is nothing.
The [documentation ](https://github.com/lucacasonato/fresh/blob/main/docs/getting-started.md#running-the-project-locally )mention `localhost:8080`

The correct address is `localhost:8000`

**Comment by lucacasonato** [comment]
Resolved now!
